// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TauResourceCalculator.BlazorServer.Data.SQLite;

#nullable disable

namespace TauResourceCalculator.BlazorServer.Data.SQLite.Migrations
{
    [DbContext(typeof(ApplicationSQLiteDbContext))]
    partial class ApplicationSQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("TauResourceCalculator.BlazorServer.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Member");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("TauResourceCalculator.BlazorServer.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("TauResourceCalculator.BlazorServer.Models.Member", b =>
                {
                    b.HasOne("TauResourceCalculator.BlazorServer.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TauResourceCalculator.BlazorServer.Models.Team", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
